ALTER TABLE "Partite"
ADD COLUMN IF NOT EXISTS "Nazionalita" character varying(3) NOT NULL DEFAULT 'ITA';

UPDATE "Partite"
SET "Nazionalita" = 'ITA'
WHERE "Nazionalita" IS NULL OR "Nazionalita" = '';

UPDATE "Partite"
SET "Nazionalita" = 'ENG'
WHERE "Id" = 153;

CREATE TABLE IF NOT EXISTS "CampoChiusure" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DataInizio" timestamp with time zone NOT NULL,
    "DataFine" timestamp with time zone NOT NULL,
    "Motivo" character varying(160) NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "IX_CampoChiusure_DataInizio_DataFine"
ON "CampoChiusure" ("DataInizio", "DataFine");
