ALTER TABLE "Tesseramenti"
ADD COLUMN IF NOT EXISTS "NatoEstero" boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "CodiceCatastaleNascita" character varying(4) NULL,
ADD COLUMN IF NOT EXISTS "NazioneNascita" character varying(100) NULL,
ADD COLUMN IF NOT EXISTS "CittaNascita" character varying(100) NULL,
ADD COLUMN IF NOT EXISTS "NazioneCittadinanza" character varying(100) NULL,
ADD COLUMN IF NOT EXISTS "NazioneResidenza" character varying(100) NULL,
ADD COLUMN IF NOT EXISTS "Cellulare" character varying(30) NULL;

CREATE TABLE IF NOT EXISTS "ComuniCatastali" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nome" character varying(150) NOT NULL,
    "Provincia" character varying(2) NULL,
    "CodiceCatastale" character varying(4) NOT NULL,
    "CodiceIstat" character varying(10) NULL,
    "Attivo" boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS "IX_ComuniCatastali_Nome_Provincia_CodiceCatastale"
ON "ComuniCatastali" ("Nome", "Provincia", "CodiceCatastale");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ComuniCatastali_CodiceCatastale"
ON "ComuniCatastali" ("CodiceCatastale");

CREATE TABLE IF NOT EXISTS "StatiEsteriCatastali" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nome" character varying(150) NOT NULL,
    "CodiceCatastale" character varying(4) NOT NULL,
    "Attivo" boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS "IX_StatiEsteriCatastali_Nome_CodiceCatastale"
ON "StatiEsteriCatastali" ("Nome", "CodiceCatastale");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_StatiEsteriCatastali_CodiceCatastale"
ON "StatiEsteriCatastali" ("CodiceCatastale");

INSERT INTO "StatiEsteriCatastali" ("Nome", "CodiceCatastale", "Attivo")
VALUES
    ('Italia', 'Z000', true),
    ('Francia', 'Z110', true),
    ('Germania', 'Z112', true),
    ('Regno Unito', 'Z114', true),
    ('Spagna', 'Z131', true),
    ('Svizzera', 'Z133', true),
    ('Romania', 'Z129', true),
    ('Marocco', 'Z330', true),
    ('Albania', 'Z100', true),
    ('Stati Uniti d''America', 'Z404', true)
ON CONFLICT ("CodiceCatastale") DO NOTHING;
