// Run against the disposable --preview server, never production.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
    const browser = await chromium.launch({channel:'msedge',headless:true});
    const context = await browser.newContext();
    await context.addCookies([{name:'VoucherTestRole',value:'Admin',url:'http://127.0.0.1:55447'}]);
    const page = await context.newPage();
    const errors=[];page.on('pageerror', e=>errors.push(e.message));
    for (const width of [390,1440]) {
        await page.setViewportSize({width,height:900});
        await page.goto('http://127.0.0.1:55447/BuoniRegalo');
        await page.screenshot({path:`.codex-build/vouchers/index-${width}.png`,fullPage:true});
        assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth), 'Index overflow');
        await page.getByRole('link',{name:'Apri buono'}).first().click();
        await page.locator('.voucher-preview').waitFor();
        await page.screenshot({path:`.codex-build/vouchers/details-${width}.png`,fullPage:true});
        assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth), 'Details overflow');
    }
    await page.goto('http://127.0.0.1:55447/BuoniRegalo');
    await page.locator('#scan-file').setInputFiles('.codex-build/vouchers/voucher.jpg.jpg');
    await page.waitForURL(/q=FMP-/);
    assert.equal(await page.locator('.voucher-item').count(),1,'Image QR search');
    await page.goto('http://127.0.0.1:55447/BuoniRegalo/Crea');
    await page.setViewportSize({width:390,height:900});
    await page.locator('#Recipient').fill('Test browser'); await page.locator('#Buyer').fill('Buyer');
    assert.equal(await page.locator('#Amount').inputValue(),'240,00');
    await page.locator('#Type').selectOption('Kids'); assert(await page.locator('#Unlimited').isChecked());
    assert.equal(await page.locator('#Amount').inputValue(),'184,00');
    await page.locator('#Type').selectOption('Adulti'); assert(!await page.locator('#Unlimited').isChecked());
    await page.locator('#Rabbit').selectOption('1');
    assert.equal(await page.locator('#Amount').inputValue(),'300,00');
    await page.locator('#Mode').selectOption('amount');
    assert(!await page.locator('#Type').isVisible());
    await page.locator('#Amount').fill('240,50');
    await page.screenshot({path:'.codex-build/vouchers/create-mobile.png',fullPage:true});
    await page.getByRole('button',{name:'Salva e visualizza anteprima'}).click();
    try { await page.waitForURL(/Dettaglio/,{timeout:10000}); }
    catch(error) { console.error(await page.locator('main').innerText()); console.error(await page.locator('input:invalid').evaluateAll(nodes=>nodes.map(n=>({id:n.id,error:n.validationMessage}))));throw error; }
    assert((await page.locator('.voucher-panel').first().innerText()).includes('240,50'),'Decimal comma');
    page.on('dialog',()=>{throw new Error('Native browser confirmation is forbidden');});
    const detailUrl=page.url();
    await page.getByRole('button',{name:'Conferma pagamento',exact:true}).click();
    const dialog=page.locator('dialog');
    assert(await dialog.isVisible());
    const box=await dialog.boundingBox();
    assert(Math.abs(box.y+box.height/2-450)<3,'Dialog vertically centered');
    await page.screenshot({path:'.codex-build/vouchers/confirm-mobile.png'});
    await dialog.getByRole('button',{name:'Torna indietro'}).click();
    assert(await page.getByRole('button',{name:'Conferma pagamento',exact:true}).isVisible());
    await page.goto('http://127.0.0.1:55447/BuoniRegalo');
    let card=page.locator('.voucher-item').filter({has:page.getByRole('heading',{name:'Test browser',exact:true})});
    assert(await card.getByRole('button',{name:'Riscatto non disponibile'}).isDisabled());
    assert(await card.locator('.voucher-payment-warning').isVisible());
    await page.goto(detailUrl);
    await page.getByRole('button',{name:'Conferma pagamento',exact:true}).click();
    await dialog.getByRole('button',{name:'Conferma pagamento',exact:true}).click();
    await page.waitForLoadState('networkidle');
    await page.goto('http://127.0.0.1:55447/BuoniRegalo');
    await card.getByRole('button',{name:'Riscatta interamente'}).click();
    await dialog.getByRole('button',{name:'Riscatta interamente'}).click();
    await page.waitForLoadState('networkidle');
    assert((await card.innerText()).includes('Riscattato'));
    await page.goto(detailUrl);
    await page.locator('input[name=reason]').first().fill('Errore di test');
    await page.getByRole('button',{name:'Annulla riscatto',exact:true}).click();
    await dialog.getByRole('button',{name:'Annulla riscatto',exact:true}).click();
    await page.waitForLoadState('networkidle');
    await page.getByText('Annulla definitivamente il buono',{exact:true}).click();
    await page.locator('input[name=reason]').fill('Solo test');
    await page.getByRole('button',{name:'Annulla buono',exact:true}).click();
    await dialog.getByRole('button',{name:'Annulla buono',exact:true}).click();
    await page.waitForLoadState('networkidle');
    await page.getByRole('button',{name:'Elimina buono',exact:true}).click();
    await dialog.getByRole('button',{name:'Elimina buono',exact:true}).click();
    await page.waitForURL(url=>!url.pathname.includes('Dettaglio'));
    assert.equal(await card.count(),0);
    assert.equal(errors.length,0,errors.join('\n'));
    await browser.close();
    console.log('PASS: mobile/desktop layout, QR, pricing, centered confirmation/cancel, unpaid disabled, list redemption, undo, cancellation and deletion.');
})().catch(e=>{console.error(e);process.exit(1);});
