using Full_Metal_Paintball_Carmagnola.Models;
using Microsoft.EntityFrameworkCore;

namespace Full_Metal_Paintball_Carmagnola.Services;

public static class TorneoSchema
{
    public static Task EnsureAsync(TesseramentoDbContext db) => db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS "Tornei" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Nome" varchar(120) NOT NULL, "Note" varchar(2000), "Data" timestamptz NOT NULL,
            "OraInizio" interval NOT NULL, "NumeroSquadre" integer NOT NULL, "NumeroGironi" integer NOT NULL,
            "AndataRitorno" boolean NOT NULL, "FasiFinali" boolean NOT NULL,
            "QualificatePerGirone" integer NOT NULL, "FinaleTerzoPosto" boolean NOT NULL,
            "RegistraPunteggio" boolean NOT NULL, "PuntiVittoria" numeric NOT NULL,
            "PuntiPareggio" numeric NOT NULL, "PuntiSconfitta" numeric NOT NULL,
            "PhotoToken" uuid NOT NULL UNIQUE, "Version" uuid NOT NULL
        );
        CREATE TABLE IF NOT EXISTS "TorneoSquadre" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "TorneoId" integer NOT NULL REFERENCES "Tornei"("Id") ON DELETE CASCADE,
            "Token" uuid NOT NULL UNIQUE, "Nome" varchar(100) NOT NULL,
            "Referente" varchar(100) NOT NULL, "Telefono" varchar(30) NOT NULL,
            "Girone" integer NOT NULL, "OrdineSpareggio" integer NOT NULL
        );
        CREATE INDEX IF NOT EXISTS "IX_TorneoSquadre_TorneoId" ON "TorneoSquadre"("TorneoId");
        CREATE TABLE IF NOT EXISTS "TorneoIncontri" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "TorneoId" integer NOT NULL REFERENCES "Tornei"("Id") ON DELETE CASCADE,
            "Fase" text NOT NULL, "Girone" integer NOT NULL, "Turno" integer NOT NULL, "Posizione" integer NOT NULL,
            "CasaId" integer REFERENCES "TorneoSquadre"("Id"), "OspiteId" integer REFERENCES "TorneoSquadre"("Id"),
            "PuntiCasa" integer, "PuntiOspite" integer, "Esito" text
        );
        CREATE INDEX IF NOT EXISTS "IX_TorneoIncontri_TorneoId" ON "TorneoIncontri"("TorneoId");
        ALTER TABLE "Tesseramenti" ADD COLUMN IF NOT EXISTS "TorneoOrigineId" integer;
        ALTER TABLE "Tesseramenti" ADD COLUMN IF NOT EXISTS "EsportatoAcsiIl" timestamptz;
        ALTER TABLE "Tesseramenti" ADD COLUMN IF NOT EXISTS "AnnoValiditaTesseramento" integer;
        CREATE TABLE IF NOT EXISTS "TorneoIscrizioni" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "TorneoSquadraId" integer NOT NULL REFERENCES "TorneoSquadre"("Id") ON DELETE CASCADE,
            "TesseramentoId" integer NOT NULL REFERENCES "Tesseramenti"("Id") ON DELETE RESTRICT,
            "NuovoTesseramento" boolean NOT NULL, "Firma" text NOT NULL, "DataCreazione" timestamptz NOT NULL,
            UNIQUE ("TorneoSquadraId", "TesseramentoId")
        );
        INSERT INTO "RolePermissions" ("RoleName", "FeatureName", "IsAllowed")
        SELECT 'Staff', 'Torneo', true
        WHERE NOT EXISTS (SELECT 1 FROM "RolePermissions" WHERE "RoleName"='Staff' AND "FeatureName"='Torneo');
        """);
}
