using Full_Metal_Paintball_Carmagnola.Models;
using Full_Metal_Paintball_Carmagnola.Services;
using Microsoft.EntityFrameworkCore;
using Npgsql;

internal static class DatabaseChecks
{
    public static async Task Run()
    {
        // Never read application credentials or touch an existing application database.
        const string adminCs = "Host=127.0.0.1;Port=55439;Database=postgres;Username=bonus_tests;SSL Mode=Disable;Timeout=3;Pooling=false";
        var name = "tornei_checks_" + Guid.NewGuid().ToString("N");
        await using var admin = new NpgsqlConnection(adminCs);
        await admin.OpenAsync();
        await using (var create = new NpgsqlCommand($"CREATE DATABASE {name}", admin)) await create.ExecuteNonQueryAsync();
        try
        {
            var cs = new NpgsqlConnectionStringBuilder(adminCs) { Database = name }.ConnectionString;
            var options = new DbContextOptionsBuilder<TesseramentoDbContext>().UseNpgsql(cs).Options;
            await using var db = new TesseramentoDbContext(options);
            // The production tournament DDL also seeds this existing application table.
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE "RolePermissions" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "RoleName" text NOT NULL, "FeatureName" text NOT NULL, "IsAllowed" boolean NOT NULL
                );
                CREATE TABLE "Tesseramenti" ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
                """);
            await TorneoSchema.EnsureAsync(db);
            await TorneoSchema.EnsureAsync(db);
            Checks.That(await db.RolePermissions.CountAsync(p => p.FeatureName == "Torneo") == 1, "Schema replay duplicated permission");
            var t = Checks.Tournament(6, 2); t.FasiFinali = true; t.QualificatePerGirone = 2; t.FinaleTerzoPosto = true;
            foreach (var s in t.Squadre) s.Id = 0;
            db.Tornei.Add(t); await db.SaveChangesAsync();
            Checks.That(t.Squadre.All(s => s.Id > 0), "Generated team IDs missing");
            TorneoEngine.GenerateGroups(t);
            foreach (var m in t.Incontri) { m.Esito = "Pareggio"; m.PuntiCasa = m.PuntiOspite = 1; }
            await db.SaveChangesAsync();
            db.ChangeTracker.Clear();
            var loaded = await db.Tornei.Include(x => x.Squadre).Include(x => x.Incontri).SingleAsync();
            Checks.That(loaded.PuntiVittoria == 2.75m && loaded.PuntiPareggio == 1.125m && loaded.PuntiSconfitta == .125m, "Decimal precision lost");
            Checks.That(TorneoEngine.Standings(loaded).Values.SelectMany(x => x).All(r => r.Punti == 2.25m && r.Giocate == 2), "Reloaded standings mismatch");
            TorneoEngine.GenerateFinals(loaded); await db.SaveChangesAsync();
            foreach (var m in loaded.Incontri.Where(m => m.Fase == "Eliminazione")) m.Esito = "Ospite";
            TorneoEngine.Advance(loaded); await db.SaveChangesAsync();
            db.ChangeTracker.Clear();
            loaded = await db.Tornei.Include(x => x.Squadre).Include(x => x.Incontri).SingleAsync();
            Checks.That(loaded.Incontri.Count(m => m.Fase == "Finale") == 1 && loaded.Incontri.Count(m => m.Fase == "Terzo posto") == 1, "Finals did not persist");
            await ControllerChecks.Run(options, loaded.Id);
            db.ChangeTracker.Clear();
            loaded = await db.Tornei.SingleAsync();
            await using (var other = new TesseramentoDbContext(options))
            {
                var stale = await other.Tornei.SingleAsync();
                loaded.Version = Guid.NewGuid(); loaded.Nome = "Updated"; await db.SaveChangesAsync();
                stale.Version = Guid.NewGuid(); stale.Nome = "Stale";
                var conflict = false;
                try { await other.SaveChangesAsync(); } catch (DbUpdateConcurrencyException) { conflict = true; }
                Checks.That(conflict, "Stale tournament version overwrote changes");
            }
            // Exercise database cascades rather than EF's tracked-entity delete ordering.
            await db.Database.ExecuteSqlInterpolatedAsync($"DELETE FROM \"Tornei\" WHERE \"Id\" = {loaded.Id}");
            Checks.That(!await db.TorneoIncontri.AnyAsync() && !await db.TorneoSquadre.AnyAsync(), "Orphans after tournament deletion");
        }
        finally
        {
            await using var drop = new NpgsqlCommand($"DROP DATABASE {name} WITH (FORCE)", admin);
            await drop.ExecuteNonQueryAsync();
        }
    }
}
